name: .NET CI

on:
  pull_request:
    branches:
      - feature/*
      - main

jobs:
  test-and-build:

    # Run on a self-hosted runner
    runs-on: [self-hosted, Linux, X64, GitHubActionsDemo-runner]

    # If you want to run on a GitHub-hosted runner, uncomment the following line and comment out the above line.
    # runs-on: ubuntu-24.04

    steps:
      - name: Show branch information
        run: |
          echo "Source: ${{ github.head_ref }}"
          echo "Target: ${{ github.base_ref }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET : If you are not using a self-hosted runner with .NET pre-installed, uncomment the following lines to set up .NET SDK.

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '10.0.x'
          
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore src/GitHubActionsDemo.csproj
          dotnet restore tests/GitHubActionsDemo.Tests.csproj

      - name: Run tests
        run: dotnet test tests/GitHubActionsDemo.Tests.csproj --no-restore --configuration Release

      - name: Build
        run: dotnet build src/GitHubActionsDemo.csproj --no-restore --configuration Release
